config/routes.rb
CmsAdmin::Application.routes.draw do

  namespace :admin do
    resources :add_packages do
    collection do
        get 'move_up'
        get 'move_down'
        get 'publish'
        get 'destroy'
        get 'remove'
        
      end
  end
end

  namespace :admin do
      resources :public_users do
        collection do
          get 'move_up'
          get 'move_down'
          get 'publish'
          get 'destroy'
          get 'remove'
        end
      end
    end
  devise_for :public_users

  root :to => 'pages#show', :id => '1'

  get 'admin' => "admin/dashboard#index"
  post 'pages_result' => "pages#result"
  get 'admin/pages/:id/posts' => "admin/pages#show_posts"

  get 'public_user_console' => "public_user_console#index"

  get 'users/sign_up' => "admin/admin#index"
  devise_for :users

  resources :pages
  resources :posts
  get '/:id' => "pages#show", :as => "pagelink"

  namespace :admin do
    resources :pages do
      collection do
        get 'move_up'
        get 'move_down'
        get 'publish'
        get 'destroy'
        get 'remove'
      end
    end
    resources :posts do
      collection do
        get 'move_up'
        get 'move_down'
        get 'new_post_for'
        get 'publish'
        get 'destroy'
        get 'remove'
      end
    end
    resources :users do
      collection do
        get 'move_up'
        get 'move_down'
        get 'publish'
        get 'destroy'
        get 'remove'
      end
    end
  end

end

app/views/admin/pages/_form.html.erb
<div class="row">
	<div class="col-sm-6">
		<%= form.input :name %>
	</div>
</div>
<%= form.input :body, as: :textile_editor %>

<hr />
<div class="row">
	<div class="col-sm-6">
		<h3>Main Image</h3>
		<% unless @page.image.blank? %>
			<div class="image_preview">
				<%= image_tag(@page.image.url(:thumb)) %>
			</div>
		<% end %>
		<%= form.input :image %>
	</div>
</div>
<hr />

<h3>Images</h3>
<div class="row images">
	<%= form.simple_fields_for :images do |image| %>
		<%= render 'image_fields', :f => image %>
	<% end %>


	<div class="links">
		<%= link_to_add_association form, :images do %>
			<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> add image
		<% end %>
	</div>
</div>
<hr />

<div class="container">
	<%= form.input :published %>
	<%= form.input :show_in_menu %>
	<%= form.input :only_for_logged_in_members %>
</div>

<hr />

app/views/admin/pages/_image_fields.html.erb
<div class="nested-fields col-sm-6">
	<% unless f.object.photo.blank? %>
		<div class="image_preview">
			<%= image_tag(f.object.photo.url(:thumb)) %>
		</div>
	<% end %>

  	<%= f.input :photo, required: false %>
  	<div class="text-right">
	  <%= link_to_remove_association f do %>
	  	<span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span> Remove Image
	 	<% end %>
	</div>
</div>

app/views/admin/pages/_list.html.erb
<% for page in @pages %>
	<div class="module_item">
		<div class="item_name">
			<%= link_to page.name, :controller => 'admin/pages', :action => 'edit', :id => page.id %>
		</div>
		<div class="module_item_actions">
			<p>
				<%= link_to(url_for(:controller => 'admin/pages', :action => 'publish', :page_id => page.id, :page => params[:page]), :format => :js, :remote => true) do %>
					<span class="glyphicon glyphicon-ok <%= page.published == true ? '' : 'dead' %>"></span>
				<% end %>
				<%= link_to :action => "edit", :id => page.id do %>
					<span class="glyphicon glyphicon-edit"></span>
				<% end %>
				<%= link_to(url_for(:controller => 'admin/pages', :action => 'destroy', :page_id => page.id, :page => params[:page]), :format => :js, :remote => true, data: { confirm: 'Are you sure?' }) do %>
					<span class="glyphicon glyphicon-trash"></span>
				<% end %>
				<%= link_to(url_for(:controller => 'admin/pages', :action => 'move_up', :page_id => page.id, :page => params[:page]), :format => :js, :remote => true) do %>
					<span class="glyphicon glyphicon-circle-arrow-up"></span>
				<% end %>
				<%= link_to(url_for(:controller => 'admin/pages', :action => 'move_down', :page_id => page.id, :page => params[:page]), :format => :js, :remote => true) do %>					
					<span class="glyphicon glyphicon-circle-arrow-down"></span>
				<% end %>
			</p>
		</div>
		<div class="clearboth"></div>
	</div>
<% end %>

app/views/admin/pages/edit.html.erb
<%= render :partial => 'admin/template/form_errors', :object => @page %>

<%= simple_form_for @page, :url => url_for(:controller => 'admin/pages', :action => 'update'), :method => 'put', :html => { :role => "form" } do |form| %>

	<%= render :partial => 'form', :object => form %>
	
	<%= submit_tag 'Submit Page', :class => 'btn btn-primary' %>

<% end %>

app/views/admin/pages/index.html.erb
<div class="module_list">
	<div class="module_actions">
		<h2>Pages</h2>
		<div class="action_items">
			<%= link_to new_admin_page_path do %>
				<p><span class="glyphicon glyphicon-plus"></span></p>
			<% end %>
		</div>
		<div class="clearboth"></div>
	</div>
	<div class="module_partial">
		<% if @pages.blank? %>
			<h3>No pages have been added yet.</h3>
		<% else %>
			<%= render :partial => 'list' %>
		<% end %>
	</div>
	<%= will_paginate @pages, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/pages/list_refresh.js.erb
$('.module_partial').html('<%= escape_javascript render(:file => 'admin/pages/_list.html.erb') %>');

app/views/admin/pages/new.html.erb
<%= render :partial => 'admin/template/form_errors', :object => @page %>
<%= simple_form_for @page, :url => url_for(:controller => 'admin/pages', :action => 'create'), :method => 'post', :html => { :role => "form" } do |form| %>

	<%= render :partial => 'form', :object => form %>
	
	<%= submit_tag 'Submit Page', :class => 'btn btn-primary' %>

<% end %>

app/views/admin/pages/show_posts.html.erb
<div class="module_list">
	<div class="module_actions">
		<h2><%= @page.name %> Posts</h2>
		<div class="action_items">
			<%= link_to(url_for(:controller => 'admin/posts', :action => 'new', :page_id => @page.id)) do %>
				Add Post <span class="glyphicon glyphicon-plus"></span>
			<% end %>
		</div>
		<div class="clearboth"></div>
	</div>
	<div class="module_partial">
		<%= render :partial => 'admin/modules/posts', :object => @posts %>
	</div>
	<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>