config/routes.rb
CmsAdmin::Application.routes.draw do

  namespace :admin do
    resources :add_packages do
    collection do
        get 'move_up'
        get 'move_down'
        get 'publish'
        get 'destroy'
        get 'remove'
        
      end
  end
end

  namespace :admin do
      resources :public_users do
        collection do
          get 'move_up'
          get 'move_down'
          get 'publish'
          get 'destroy'
          get 'remove'
        end
      end
    end
  devise_for :public_users

  root :to => 'pages#show', :id => '1'

  get 'admin' => "admin/dashboard#index"
  post 'pages_result' => "pages#result"
  get 'admin/pages/:id/posts' => "admin/pages#show_posts"

  get 'public_user_console' => "public_user_console#index"

  get 'users/sign_up' => "admin/admin#index"
  devise_for :users

  resources :pages
  resources :posts
  get '/:id' => "pages#show", :as => "pagelink"

  namespace :admin do
    resources :pages do
      collection do
        get 'move_up'
        get 'move_down'
        get 'publish'
        get 'destroy'
        get 'remove'
      end
    end
    resources :posts do
      collection do
        get 'move_up'
        get 'move_down'
        get 'new_post_for'
        get 'publish'
        get 'destroy'
        get 'remove'
      end
    end
    resources :users do
      collection do
        get 'move_up'
        get 'move_down'
        get 'publish'
        get 'destroy'
        get 'remove'
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

         # acts_as_list

end

app/controllers/admin/users_controller.rb
module Admin
  
  class UsersController < ApplicationController
  	before_filter :authenticate_user!

  	layout 'admin'

	  before_action :set_user, only: [:show, :edit, :update]

	  # GET /users
	  # GET /users.json
	  def index
	    @users = User.paginate(:page => params[:page], :per_page => 20)
	  end

	  # GET /users/new
	  def new
	    @user = User.new
	  end

	  # GET /users/1/edit
	  def edit
	  end

	  # POST /users
	  # POST /users.json
	  def create
	    @user = User.new(:email => params[:user][:email], :password => params[:user][:password], :password_confirmation => params[:user][:password_confirmation])

      if @user.save
      	flash[:notice] = "User successfully created."
        redirect_to :controller => 'admin/users'
      else
        render action: 'new'
      end
	  end

	  # PATCH/PUT /users/1
	  # PATCH/PUT /users/1.json
	  def update

	    if user_params[:password].blank?
	      user_params.delete("password")
	      user_params.delete("password_confirmation")
	    end


	    if @user.update(user_params)
	    	flash[:notice] = "User successfully updated."
	      redirect_to :action => 'edit'
	    else
	      render action: 'edit'
	    end
	  end

	  # DELETE /users/1
	  # DELETE /users/1.json
	  def destroy
	  	@user = User.find(params[:user_id])

	    unless @user.id == 1
	      @user.destroy
	    end

	    respond_to do |format|
        format.js { list_refresh }
      end
	  end

	  private

	  	def list_refresh
        @users = User.paginate(:page => params[:page], :per_page => 20)
        return render(:file => 'admin/users/list_refresh.js.erb')
      end

	    # Use callbacks to share common setup or constraints between actions.
	    def set_user
	      @user = User.find(params[:id])
	    end

	    # Never trust parameters from the scary internet, only allow the white list through.
	    def user_params
	      params.require(:user).permit(:is_admin, :email, :password, :password_confirmation, :remember_me)
	    end
	end


end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <label>Email</label>
      <%= form.text_field :email, :class => "form-control", :placeholder => "Email Address" %>
    </div>
  </div> 
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <label>Password</label>
      <%= form.text_field :password, :class => "form-control", :placeholder => "Secret Password", :type => "password" %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <label>Password Confirmation</label>
      <%= form.text_field :password_confirmation, :class => "form-control", :placeholder => "Secret Password", :type => "password" %>
    </div>
  </div>
</div>

app/views/admin/users/_list.html.erb
<% for user in @users %>
  <div class="module_item">
    <div class="item_name">
      <%= link_to user.email, :controller => 'admin/users', :action => 'edit', :id => user.id %>
    </div>
    <div class="module_item_actions">
      <p>
        <%= link_to :action => "edit", :id => user do %>
          <span class="glyphicon glyphicon-edit"></span>
        <% end %>
        <%= link_to(url_for(:controller => 'admin/users', :action => 'destroy', :user_id => user.id, :page => params[:page]), :format => :js, :remote => true, data: { confirm: 'Are you sure?' }) do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </p>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= render :partial => 'admin/template/form_errors', :object => @user %>

<%= simple_form_for @user, :url => url_for(:controller => 'admin/users', :action => 'update'), :method => 'put', :html => { :role => "form" } do |form| %>

	<%= render :partial => 'form', :object => form %>
	
	<%= submit_tag 'Submit', :class => 'btn btn-primary' %>

<% end %>

app/views/admin/users/index.html.erb
<div class="module_list">
  <div class="module_actions">
    <h2>Users</h2>
    <div class="action_items">
      <%= link_to new_admin_user_path do %>
        <p><span class="glyphicon glyphicon-plus"></span></p>
      <% end %>
    </div>
    <div class="clearboth"></div>
  </div>
  <% unless @users.blank? %>
    <div class="module_partial">
      <%= render :partial => 'admin/users/list' %>
    </div>
  <% end %>
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/users/list_refresh.js.erb
$('.module_partial').html('<%= escape_javascript render(:file => 'admin/users/_list.html.erb') %>');

app/views/admin/users/new.html.erb
<%= render :partial => 'admin/template/form_errors', :object => @user %>
<%= simple_form_for @user, :url => url_for(:controller => 'admin/users', :action => 'create'), :method => 'post', :html => { :role => "form" } do |form| %>

	<%= render :partial => 'form', :object => form %>
	
	<%= submit_tag 'Submit', :class => 'btn btn-primary' %>

<% end %>